# receivers:
#   otlp:
#     protocols:
#       http:

# exporters:
#   prometheus:
#     endpoint: "0.0.0.0:8889"
#     const_labels: {}
#   otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
#     endpoint: http://jaeger:4317
#     # tls:
#     #   insecure: true
#   otlp:
#     endpoint: ${OTEL_NEW_RELIC_EXPORTER_OTLP_ENDPOINT}
#     headers:
#       api-key: ${OTEL_NEW_RELIC_EXPORTER_API_KEY}

# processors:
#   batch:
#   memory_limiter:
#     check_interval: 1s
#     limit_percentage: 65
#     spike_limit_percentage: 50
#   resourcedetection:
#     detectors: [gcp]
#     timeout: 10s

# extensions:
#   health_check:
#   pprof:
#     endpoint: :1888
#   zpages:
#     endpoint: :55679

# service:
#   extensions: [pprof, zpages, health_check]
#   pipelines:
#     traces:
#       receivers: [otlp]
#       processors:
#         - batch
#       exporters:
#         - otlp/jaeger
#         - otlp
#     metrics:
#       receivers: [otlp]
#       processors:
#         - memory_limiter
#         - batch
#       exporters:
#         - prometheus
#         - otlp
receivers:
  otlp:
    protocols:
      http:
      grpc:
  # postgresql:
  #   endpoint: postgres:5432
  #   transport: tcp
  #   username: postgres
  #   password: postgres
  #   databases:
  #     - product_service_db
  #   collection_interval: 10s
  #   tls:
  #     insecure: true

exporters:
  # otlp/jaeger:# Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
  # endpoint: jaeger:4317
  # tls:
  #   insecure: true
  otlphttp:
    endpoint: http://jaeger-container:14268/api/traces
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels: {}
    # tls:
    #   insecure: true

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 50
  resourcedetection:
    detectors: [gcp]
    timeout: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - batch
      exporters:
        # - otlp/jaeger
        # - otlphttp
        - otlp/jaeger
    metrics:
      receivers: [otlp]
      processors:
        - batch
      exporters:
        - prometheus
